Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# --- Saezlab tools ---
# https://decoupler-py.readthedocs.io/
import gzip
import os
import shutil
import tempfile
import urllib.request

import decoupler as dc
import numpy as np

# https://omnipathdb.org/
import omnipath as op

# Additional packages
import pandas as pd

# --- Additional libs ---
# Pydeseq for differential expression analysis
from pydeseq2.dds import DefaultInference, DeseqDataSet
from pydeseq2.ds import DeseqStats

# https://saezlab.github.io/
import corneto as cn

cn.info()
------------------

----- stderr -----
/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
----- stderr -----
2025-07-03 12:15:33 | [INFO] Downloading data from `https://omnipathdb.org/queries/enzsub?format=json`
----- stderr -----
2025-07-03 12:15:34 | [INFO] Downloading data from `https://omnipathdb.org/queries/interactions?format=json`
----- stderr -----
2025-07-03 12:15:38 | [INFO] Downloading data from `https://omnipathdb.org/queries/complexes?format=json`
----- stderr -----
2025-07-03 12:15:39 | [INFO] Downloading data from `https://omnipathdb.org/queries/annotations?format=json`
----- stderr -----
2025-07-03 12:15:40 | [INFO] Downloading data from `https://omnipathdb.org/queries/intercell?format=json`
----- stderr -----
2025-07-03 12:15:40 | [INFO] Downloading data from `https://omnipathdb.org/about?format=text`
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 20[0m
[1;32m     16[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mpandas[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mpd[39;00m
[1;32m     18[0m [38;5;66;03m# --- Additional libs ---[39;00m
[1;32m     19[0m [38;5;66;03m# Pydeseq for differential expression analysis[39;00m
[0;32m---> 20[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mpydeseq2[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdds[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m DefaultInference, DeseqDataSet
[1;32m     21[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mpydeseq2[39;00m[38;5;21;01m.[39;00m[38;5;21;01mds[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m DeseqStats
[1;32m     23[0m [38;5;66;03m# https://saezlab.github.io/[39;00m

[0;31mModuleNotFoundError[0m: No module named 'pydeseq2'

